import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans, Public_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--display-family",
});

const public_sans = Public_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--text-family",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${open_sans.variable} ${public_sans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
